In [33]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score
import math
from sklearn.datasets import load_iris

# Logistic Regression

In [34]:
iris=load_iris()

x=iris.data
y=iris.target

print(x)
print(y)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=341)
print(x_train)
print(y_train)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [35]:
linReg=LogisticRegression()

linReg.fit(x_train,y_train)
print(y_train)

y_pred=linReg.predict(x_test)

print(y_test)
print(y_pred)

k=linReg.coef_
b=linReg.intercept_
print("y=",k,"x+",b)

print(accuracy_score(y_test,y_pred))

[1 0 0 1 1 0 0 0 0 1 2 1 2 2 2 1 1 1 2 0 2 2 1 1 0 1 2 1 0 1 0 0 0 2 2 2 2
 2 1 0 2 0 2 2 2 1 2 0 0 2 0 2 1 0 0 2 0 2 1 2 2 1 0 1 1 0 1 2 1 0 2 2 2 1
 0 2 0 2 2 2 1 0 1 0 1 1 0 2 0 1 2 2 0 1 0 1 1 1 1 0 2 1 1 2 0 1 1 2 1 1 0
 2 1 2 0 0 0 0 2 2]
[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 2 1 0 0 2 2 1 0 0 1 2 2 0]
[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 1 1 0 0 1 2 1 0 0 1 2 2 0]
y= [[-0.47460882  0.81428394 -2.35641366 -1.01160889]
 [ 0.29129613 -0.46052999 -0.1334963  -0.85497412]
 [ 0.18331269 -0.35375395  2.48990996  1.86658301]] x+ [  9.94039946   3.52037127 -13.46077073]
0.9333333333333333


# Naive Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB
nbmodel=GaussianNB()
nbmodel.fit(x_train,y_train)

y_pred=nbmodel.predict(x_test)

print(y_test)
print(y_pred)

print(accuracy_score(y_test,y_pred))

[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 2 1 0 0 2 2 1 0 0 1 2 2 0]
[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 1 1 0 0 1 2 1 0 0 1 2 2 0]
0.9333333333333333


# KNN

In [37]:
from sklearn.neighbors import KNeighborsClassifier

knnmodel=KNeighborsClassifier(n_neighbors=5)

knnmodel.fit(x_train,y_train)

y_pred=knnmodel.predict(x_test)

print(y_pred)
print(y_test)

print(accuracy_score(y_test,y_pred))

[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 1 1 0 0 1 2 1 0 0 1 2 2 0]
[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 2 1 0 0 2 2 1 0 0 1 2 2 0]
0.9333333333333333


# Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier

dtmodel=DecisionTreeClassifier()

dtmodel.fit(x_train,y_train)

y_pred=dtmodel.predict(x_test)

print(accuracy_score(y_test,y_pred))


0.9333333333333333


# Random Forest

In [39]:
from sklearn.ensemble import RandomForestClassifier

rfmodel=RandomForestClassifier()

rfmodel.fit(x_train,y_train)

y_pred=rfmodel.predict(x_test)

print(y_pred)
print(y_test)

print(accuracy_score(y_test,y_pred))

[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 1 1 0 0 1 2 1 0 0 1 2 2 0]
[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 2 1 0 0 2 2 1 0 0 1 2 2 0]
0.9333333333333333


# SVM

In [40]:
from sklearn import svm

svmmodel=svm.SVC()

svmmodel.fit(x_train,y_train)

y_pred=svmmodel.predict(x_test)

print(y_test)
print(y_pred)

print(accuracy_score(y_test,y_pred))

[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 2 1 0 0 2 2 1 0 0 1 2 2 0]
[0 0 0 0 1 2 1 1 1 0 1 2 2 1 0 0 1 1 1 0 0 2 2 1 0 0 1 2 2 0]
0.9666666666666667
